channels:
- defaults
- conda-forge
dependencies:
- python=3.6.12
- scikit-learn=0.23.2
- tensorflow>=2.0
- pytorch>1.0,<2.0
- boto
- pip
- pip:
  - mlflow
  - dask>1.0
  - cloudpickle==1.6.0
name: mlflow-complex-env
